# -*- coding: utf-8 -*-
"""NLP Course.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJG7eJWWkjS6lKeubyLKeO8pv7kh_dh7
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    'I love my dog',
    'I love my cat',
    'Your love my dog!',
    'Do you think my dog is amazing?'
]

tokenizer = Tokenizer(num_words = 100)
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)

print(word_index)
print(sequences)